[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
program = "6Shf4n6CqC2Wyt21YK6Kfw5rtDn2GWKGURvRdysqV92h"

[programs.devnet]
program = "6Shf4n6CqC2Wyt21YK6Kfw5rtDn2GWKGURvRdysqV92h"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
